services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/import.sql:/docker-entrypoint-initdb.d/02_import.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost -p 5432"]
      interval: 10s
      retries: 15 
      timeout: 5s
      start_period: 0s

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_API_PORT=11434
      - OLLAMA_API_HOST=localhost
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama_data:/ollama
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 5 &&
        ollama pull gemma3:4b &&
        wait
      "
      
volumes:
  postgres_data:
    driver: local
  ollama_data:
     driver: local
