services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - API_PORT=80
      - REDIS_HOST=redis
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    networks:
      - pwnd-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_HOST=8080
    networks:
      - pwnd-network

  redis:
    image: redis:latest
    networks:
      - pwnd-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pwnd-network

  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_API_PORT=11434
      - OLLAMA_API_HOST=localhost
    volumes:
      - ollama_data:/ollama
    networks:
      - pwnd-network
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - pwnd-network

volumes:
  postgres_data:
    driver: local
  ollama_data:
     driver: local
networks:
  pwnd-network:
    driver: bridge
