version: "3.9"

services:
  # api:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - API_PORT=8080
  #     - REDIS_HOST=redis
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_HOST=8080
